columnSuffix: null
handle: score
instructions: null
name: Score
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 10
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: 1
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
